In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
d=np.random.random((2,2))
print(d)

[[0.58344934 0.44047684]
 [0.85068636 0.69713824]]


In [16]:
e=np.arange(0,20,5)
print(e)

[ 0  5 10 15]


In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [5]:
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [6]:
print(arr.ndim)

2


In [7]:
print(arr.dtype)

int64


In [8]:
print(arr.shape)

(3, 4)


In [9]:
print(arr.size)

12


In [10]:
newtype=arr.astype('f')
print("\n convert array.\n",newtype)
print("\nconvert array type .\n",newtype.dtype)


 convert array.
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

convert array type .
 float32


In [12]:
size=len(arr)
print("\n size of the array",size)


 size of the array 3
