In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)


 one dimensional array 
 [1 2 3 4]


In [1]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [1]:
import numpy as np
c=np.zeros((3,5))
print(c)


 value with all zeros 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
import numpy as np
e=np.arange(8,29,3)
print(e)

[ 8 11 14 17 20 23 26]


In [3]:
import numpy as np
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)


 three dimensional array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np
d=np.random.random((3,3))
print(d)

[[0.88686827 0.03461189 0.71388723]
 [0.64467327 0.84422295 0.25504649]
 [0.45679899 0.52208794 0.07102166]]


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
flat=arr.flatten()
print(arr)
print(flat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
import numpy as np
print(arr.dtype)

int64


In [10]:
import numpy as np
print(arr.size)

12


In [16]:
import numpy as np
print(arr.ndim)


 no of dimensions 
 3


In [17]:
import numpy as np
print(arr.shape)


 shape of array 
 (3, 4)
