In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
slice1=arr[2:8:2]
print(slice1)

[3 5 7]


In [5]:
rev_arr=arr[::-1]
print(rev_arr)

[8 7 6 5 4 3 2 1]


## a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3:2])
print(a[0::2])
print(a[::])
print(a[2:2:2])

In [1]:
import numpy as np
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [3]:
reversed_array=arr[::-1]
print(reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [15]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>>25])
print(arr[[1,3]])


10
50
50
[20 30 40]
[10 10 10 10 10]
[20 40]


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [17]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
